//
// Created by fanzhengchen on 6/29/17.
//

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Main
 * Method:    doubleString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Main_doubleString
        (JNIEnv *, jobject, jstring);


/*
 * Class:     Main
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Main_release
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif

